// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBexewJg5Q8PupG-BkPLuwOiWRCnEzy5l8',
    appId: '1:915946093612:android:0453aec6e0e8720a866589',
    messagingSenderId: '915946093612',
    projectId: 'mchat2-6f791',
    storageBucket: 'mchat2-6f791.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQnxFZyo2HvyalnN2hz39yj-5YW0Zs2l4',
    appId: '1:915946093612:web:686b2364f1a28056866589',
    messagingSenderId: '915946093612',
    projectId: 'mchat2-6f791',
    authDomain: 'mchat2-6f791.firebaseapp.com',
    storageBucket: 'mchat2-6f791.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlVvTMyTdUt2c0htFvuMScWwgHXCUllgA',
    appId: '1:915946093612:ios:3a6a92c1c936f731866589',
    messagingSenderId: '915946093612',
    projectId: 'mchat2-6f791',
    storageBucket: 'mchat2-6f791.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlVvTMyTdUt2c0htFvuMScWwgHXCUllgA',
    appId: '1:915946093612:ios:3a6a92c1c936f731866589',
    messagingSenderId: '915946093612',
    projectId: 'mchat2-6f791',
    storageBucket: 'mchat2-6f791.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwVlESBHazhO6ThOa7i4IOP7bEph94YA4',
    appId: '1:915946093612:web:6b6849c90d0165f6866589',
    messagingSenderId: '915946093612',
    projectId: 'mchat2-6f791',
    authDomain: 'mchat2-6f791.firebaseapp.com',
    storageBucket: 'mchat2-6f791.appspot.com',
  );

}